import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/providers/theme-provider";
import { ToastProvider } from "@/providers/toast-provider";

const font = Roboto({ 
  weight: ['100','300','400', '500', '700', '900'],
  subsets: ["latin"],
display: 'swap' 
});

export const metadata: Metadata = {
  title: "Koinonia | Download your favourite sermon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      <html lang="en" suppressHydrationWarning={true}>
        <body className={font.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
            storageKey="koinonia-app-1"
          >
            <ToastProvider />
            {children}
          </ThemeProvider>
        </body>
      </html>
    
  );
}